language: cpp

compiler:
  - gcc
  - clang

before-install:
  - sudo apt-get libglu1-mesa-dev libgl1-mesa-dev libxmu-dev libxi-dev libxext-dev libx11-dev xorg-x11-devel x11-devel

script:
  - cd libs/sources; make
  - cd ../..
  - cd akari/build; make
